### ISSUE TITLE
map only works after getting value once

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#2]
```haxe
var state = new State(0);
state.observe().changed.handle(function(_) trace('state changed: ${state.value}'));

var mapping = state.observe().map(function(_) return state.value + 1);
// trace(mapping.value); // uncomment this line to make it work
mapping.changed.handle(function(_) trace('mapping changed ${mapping.value}'));

state.set(1);
state.set(2);
```

The above code prints:

```
state changed: 1
state changed: 2
```

which means the map is not working. 

It is most likely caused by the valid filter [here](https://github.com/haxetink/tink_state/blob/553187c/src/tink/state/Observable.hx#L222)

**Comment by kevinresol** [comment]
Well, actually the valid filter is a bit problematic. I need to call `mapping.value` every time `changed` triggers in order to get the next `changed` signal. Is there any particular reason the filter is in place?

**Comment by back2dos** [comment]
I'm sorry for the confusion, the changed signal is for internal use only. You need to use `bind` to subscribe to changes. The rest should work as expected (I hope).
