### ISSUE TITLE
ObservableMap observes added/removed key

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#20]
Somehow I would like to have a signal to notify when a key is added/removed. For now I can observe the key list and compare the old vs new one but doesn't seems to be very smart.

**Comment by back2dos** [comment]
You mean [`observe`](https://github.com/haxetink/tink_state/blob/master/src/tink/state/ObservableMap.hx#L44)? Which reminds me I really need to clean up the API here :D

Also `Observable.auto(() -> map.exists(key))` / `Observable.auto(() -> map.get(key))` should work too.

If it's a `Signal` you want though, we could make [`changes`](https://github.com/haxetink/tink_state/blob/master/src/tink/state/ObservableBase.hx#L9) public and you can take it from there.

**Comment by kevinresol** [comment]
Nope, it is about a new key being added without knowing the key in advance. I have now an implementation locally that overrides the set and remove method to trigger a signal accordingly. 

https://github.com/why-haxe/why-ble/blob/246e161/src/why/ble/Central.hx#L66-L80

**Comment by back2dos** [comment]
Oh, well the I guess you want the signal that is there already and filter on when exactly one of `from` and `to` is `None`.

**Comment by kevinresol** [comment]
aha, now I see how it works
