### ISSUE TITLE
ObservableArray: filter(), sort() etc. missing

### ISSUE THREAD

**Issue by cambiata** [haxetink/tink_state#32]

**Comment by back2dos** [comment]
Hmm, actually ... I do get what `sort` should do. But what would `filter` do? Construct a new observable array? Or be a filtered readonly view on the original array?

**Comment by cambiata** [comment]
I filter all the time, for example in interactive admin-views where I want to filter a list for certain type or date range - or just any interactive search-item view. 

I have my own static extension for this now, where I just return a new observable array from the filtered content:
```
inline function filter<T>(oa:ObservableArray<T>, f:(item:T) -> Bool):ObservableArray<T> {
	return new ObservableArray(oa.toArray().filter(f));
}
```
Is there an alternative, maybe cheaper, approach? A "readonly view on the original array" would be fine in many cases, I guess.  Does such a "readonly" collection type exist for now? (I only know of tink.pure.List or tink.state.ObservableArray (and -Map) as valid collectiontypes in views...)
