### ISSUE TITLE
Debugging tools.

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_state#39]
Some helpers to debug observables would be good, in particular getting the dependency graphs of auto-observables.

**Comment by Neverbirth** [comment]
Knowing which observable triggered an update when there are multiple observables involved would be really handy for troubleshooting in complex scenarios.

**Comment by back2dos** [comment]
This is largely done as far as tink_state is concerned.

Compile with `-D tink_state.debug` and use `tink.state.debug.Logger` to track anything you may be interested in.

**Comment by back2dos** [comment]
Also worth mentioning: with `-D tink_state.debug` you can call `someObservable.dependencyTree()` to get its dependencies.
