### ISSUE TITLE
Add an equivalent of Promised for Future, without the Failed state

### ISSUE THREAD

**Issue by nadako** [haxetink/tink_state#46]
From the gitter chat:

> I wonder if tink_state should/could have a `Futuristic` (or something) type, which is like `Promised` but without `Failed` state, basically an observable for `Future` rather than `Promise`.

> in our codebase we use `Future` instead of `Promise` quite a lot, because in a lot of cases the error case is handled globally and leads to a "something went wrong, reload your game" modal dialog, especially when it comes to backend communication. so there's no error handling on a higher level. now if some model have data initialized like this, it can only have two states: `Loading` and `Done` :)

**Comment by kevinresol** [comment]
How about just:

```haxe
enum FutureState<T> {
  Loading;
  Ready(value:T);
}
```

and replace `Promised`... (though breaking)

**Comment by nadako** [comment]
Would work for me, sounds easy enough to match for promises too: `case Ready(Success(blah))` instead of `case Done(blah)`. But yep I bet it's super breaking.

**Comment by kevinresol** [comment]
I think we can introduce a define for easier transition

**Comment by back2dos** [comment]
See #53 for a non-breaking attempt.

**Comment by back2dos** [comment]
Ok, I just went with #53
