### ISSUE TITLE
Store previous value in Promised.Loading?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#5]
So essentially make it `Loading(prev:Option<T>)`
I found this useful in coconut, because I don't want to clear up the visual while the value is refreshing.

**Comment by back2dos** [comment]
Good idea. It will be a breaking change, so I'll have to think about how to time it.

For now I would suggesting using something like this [somewhat hideous higher level component](https://gist.github.com/back2dos/ca262deaca81ba03d9a6c201af89f9a1) to deal with not only that, but also keep around a copy of the old view for making nice transitions. Note that hxx allows you to use it like so:

```haxe
var user:Observable<Promised<{ name:String }>> = ...;

coconut.Ui.hxx('
  <Swapper class="something" data={user}>
    <renderData>
       <p>Hello {name}</p>
    </renderData>
  </Swapper>
');

//alternatively (if you wish to name the state):

coconut.Ui.hxx('
  <Swapper class="something" data={user}>
    <renderData {...u}>
       <p>Hello {u.name}</p>
    </renderData>
  </Swapper>
'); 
```

If you don't name the argument (as in the first example), you can refer to it as `$`.

**Comment by kevinresol** [comment]
Well, this workaround looks soooo complicated... and wrapping the content in some extra div may make some css frameworks to fail...

**Comment by kevinresol** [comment]
And if I somehow access the promised data before the swapper, the swapper stack will be gone. Probably because the swapper has been replaced by a new instance.

```haxe
function render() '
	<div class="ui container vertical segment">
		<div class=${"ui icon input" + (search.results == Loading ? " loading" : "")}>
			<input oninput=${onInput.bind(search)} placeholder="搜尋"/>
			<i class="search icon"/>
		</div>
		
		<Swapper class="" data=${search.results}>
			<renderData {...d}>
				${Std.string(d)}
			</renderData>
		</Swapper>
	</div>
';
```

Removing ` + (search.results == Loading ? " loading" : "")` will make it work as expected

**Comment by back2dos** [comment]
If you give the swapper a key that should avoid replacing it.

**Comment by kevinresol** [comment]
> If you give the swapper a key that should avoid replacing it.

Yeah that's it. Great.

**Comment by back2dos** [comment]
Ok, uhm, I wanted to do something about it, but it led me to wonder, what do we do in [PromisedTools.next](https://github.com/haxetink/tink_state/blob/d7c33b27f4b90d879ef34dda9dd097705c4bb25f/src/tink/state/Promised.hx#L14) if a previous value is available? Rather `f(prev)` or stick with the `Promise.NEVER`?

**Comment by kevinresol** [comment]
Well I guess it should be `f(prev)`, or even better, a cached value of that (because it may not have resolved yet).
But since the function itself is pure and has no memory. I think `f(prev)` is the way....

**Comment by kevinresol** [comment]
Or just expose it and let user decide?

**Comment by back2dos** [comment]
This is now supported in a slightly different way. You can define computations as `Option<T>->T` and `Option<T>->Promise<T>` in which case the option will contain the last value and the last `Done` value respectively.

In `coconut.data` this is currently supported via `$last` (better ideas are highly welcome).

It doesn't smoothly cover all the cases of having the previous value for `Promised`, i.e. if you consume an external `Promised` you have to resort to this:

```haxe
@:external var data:Promised<Foo>;
@:loaded var withPrevious:Foo = switch [data, $last] {
  case [Done(v), _] | [_, Some(v)]: Success(v);
  case [Failed(e), _]: e;
  case [Loading, _]: Promise.NEVER;
}
```

So, you think this will this work for you? ^^

**Comment by kevinresol** [comment]
I will check if I can use that in [InfiniteList](https://github.com/kevinresol/coconut.ds/blob/master/src/coconut/ds/InfiniteList.hx) to get rid of the `cache` field

**Comment by back2dos** [comment]
I'll just assume this works. Feel free to close otherwise ;)
