### ISSUE TITLE
What API replaces observableLength and observableValues?

### ISSUE THREAD

**Issue by Aszusz** [haxetink/tink_state#59]
Hi,
I'm trying to figure out how to use `ObservableArray` for add/remove item notifications. I am using tink_state 1.0.0-beta.2, but also tried 0.11.1. In the older version there were (already deprecated) properties `observableLength` and `observableValues`. Binding to those properties works correctly for me in 0.11.1. In 1.0.0-beta.2 they no longer work and I cannot figure out what API should I use instead.

**Comment by nadako** [comment]
I think `Observable.auto(() ->a.length)` should work?

**Comment by Aszusz** [comment]
OK, so if I want to observe the values should I create Observable first, like this?
```
var todos = new ObservableArray<Todo>()
var obs = Observable.auto(() -> {todos.toArray();});
obs.bind(values -> listView.dataProvider = new ArrayCollection(values));
```
Is there any way to get more granular updates (added/deleted/updated) so I can pass them on to the rendering engine (Feathers UI)?

**Comment by back2dos** [comment]
I decided to undeprecate them after all. As for granular observation, the issue is tracked via #49
