### ISSUE TITLE
LinkObject import is missing in the Binding.hx

### ISSUE THREAD

**Issue by hansagames** [haxetink/tink_state#65]
Hi,

noticed that `LinkObject` is being used in `src/tink/state/internal/Binding.hx`

but there is no import from `tink.core.Callback.LinkObject`,

because of that could not compile my app, is it intentional? and I am missing something or its bug ?

thank you

**Comment by back2dos** [comment]
Well, the tests pass and the reason they do is that the [import happens in `import.hx`](https://github.com/haxetink/tink_state/blob/b01eb8bd47f7264420604b5f8816dde69e5dec55/src/tink/state/import.hx#L2). Which versions of haxe, tink_core and tink_state are you using?

**Comment by hansagames** [comment]
hi @back2dos 

`tink_core=2.0.2`
`tink_state=1.0.0-beta.3`
`haxe=4.2.2`

**Comment by hansagames** [comment]
but if its intetion will try to check maybe its some cache issue or so

**Comment by hansagames** [comment]
Will close as after removing all libs and haxe, after reinstall didnt get any error anymore
