### ISSUE TITLE
Observable not firing callbacks for non-direct bindings

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#7]
Comes from here: https://github.com/haxetink/tink_multipart/commit/c6ce308c70a0208c9a7845bd5182c2d00ae82cac

Any idea?

**Comment by back2dos** [comment]
Certainly a creative use of tink_state :D

I'm quite surprised you didn't face this in you RN apps. Or does the runtime provide RAF?

**Comment by kevinresol** [comment]
> does the runtime provide RAF

Yes I think so.
