### ISSUE TITLE
Obervable.ofPromise does not fire binding?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#76]
In the following the binding only fires Loading, but expected to also fire Done(1)
```haxe
final p = Promise.trigger();
final o = Observable.auto(() -> p.asPromise());

o.bind(v -> trace(Std.string(v)), Scheduler.direct); 
trace(Std.string(o.value)); // Loading
p.resolve(1);
trace(Std.string(o.value)); // Done(1)
```

**Comment by kevinresol** [comment]
@back2dos this one seems critical, can you have a look please?

**Comment by kevinresol** [comment]
or perhaps we should just merge v1

**Comment by back2dos** [comment]
Myeah, I'm struggling to make the v1 tests pass with coconut.ui, so that's gonna take a while. In the meantime, it's fixed on master ;)
