### ISSUE TITLE
Generate warnings when state is updated within bind.

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_state#8]
There should be a way to opt out of it, but generally speaking if changes to observable A trigger an update of state B, then B should be computed from A. 

While previously it would cause the scheduler to enter an eager loop, this was now fixed in https://github.com/haxetink/tink_state/commit/be5a6200a7945a06a1e89c7f9314a8a3e41f7b2f. It is now even possible to have cycles such as this one on async platforms:

```haxe
    var s1 = new State(0),
        s2 = new State(0);
    s1.observe().bind(function (v) s2.set(v + 1));
    s2.observe().bind(function (v) s1.set(v + 1));
```

It will trash the CPU, but it will not block it. When updates take longer than 10ms, the next batch of updates is scheduled to run later. The above cycle is of course absolute non-sense, but if there's an exit condition, it will be reached eventually, without blowing up everything else in the process.

**Comment by gene-pavlovsky** [comment]
It sounds like one might implement coroutines by doing something like in the example.

**Comment by back2dos** [comment]
Well, not quite. One appeal of coroutines is that can be suspended at almost no cost. The above cycle will busily loop on the CPU.

**Comment by gene-pavlovsky** [comment]
Fair enough
