### ISSUE TITLE
Get rid of implicit conversions (at least partially).

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_state#9]
Sometimes weird things happen because of the from/to that Observable and State have with plain values. The latter hasn't yet cause problems for me, but the former can lead to some headaches, in particular the `@:from T` for `Observable<T>`.

I propose instead to introduce something like:

```haxe
@:forward
abstract Var<T>(Observable<T>) from Observable<T> to Observable<T> {
  @:from static function ofConst<T>(value:T):Var<T> return Observable.const(value);
}
```

Migration path would be to add this in the next release and generate warnings when implicit conversion from constants to observables is used, and then remove it relatively soon after. Thoughts?

CC @kevinresol @dmitry-kuzovatkin @gene-pavlovsky

**Comment by gene-pavlovsky** [comment]
Can you show a use case of this new `Var`?
Personally I agree that something should be done, because while it's nice to have implicit conversion, if I have to write `.value` in some cases to avoid problems, it's not nice at all. Either it work in all cases or I would prefer to be always explicit.

**Comment by back2dos** [comment]
Well, the only point of `Var` is really that if you have a public API that consumes observables, calling code won't have to wrap constants manually, as is the case now. Whether or not you'll use it is a different question ;)

**Comment by kevinresol** [comment]
I didn't rely on the implicit `@:from`, I think. So should be fine for me.

**Comment by gene-pavlovsky** [comment]
Sounds good to me, after you've explained things on Skype :)

**Comment by gene-pavlovsky** [comment]
Copy-pasted the `@:deprecated` warning into our application and found several issues where plain values were inadvertently passed where an observable should have been passed. This is definitely a worthy issue :)
